---Understanding my data
select * from `workspace`.`default`.`car_sales_data_clean` limit 100;

--- Check how many non-null values exist per column
SELECT 
  COUNT(*) AS total_rows,
  COUNT(make) AS make_count,
  COUNT(model) AS model_count,
  COUNT(sellingprice) AS price_count,
  COUNT(odometer) AS odometer_count,
  COUNT(state) AS state_count,
  COUNT(transmission) AS transmission_count,
  COUNT(color) AS color_count
FROM `workspace`.`default`.`car_sales_data_clean`;

-- Check different car brands (make)
SELECT DISTINCT make
FROM `workspace`.`default`.`car_sales_data_clean`
ORDER BY make;

--- Checking different fuel/body types
SELECT DISTINCT body
FROM `workspace`.`default`.`car_sales_data_clean`;

--- Check transmission types
SELECT DISTINCT transmission
FROM `workspace`.`default`.`car_sales_data_clean`;

--- Count number of cars sold per state (region)
SELECT state, COUNT(*) AS total_sales
FROM `workspace`.`default`.`car_sales_data_clean`
GROUP BY state
ORDER BY total_sales DESC;

-- Understand price range (min, max, average)
SELECT 
  MIN(sellingprice) AS min_price,
  MAX(sellingprice) AS max_price,
  AVG(sellingprice) AS avg_price
FROM `workspace`.`default`.`car_sales_data_clean`;

--- Check mileage distribution
SELECT 
  MIN(odometer) AS min_mileage,
  MAX(odometer) AS max_mileage,
  AVG(odometer) AS avg_mileage
FROM `workspace`.`default`.`car_sales_data_clean`;

-- Extract year from sale date to understand time trends
SELECT 
  YEAR(TO_TIMESTAMP(SUBSTRING(saledate, 5), 'MMM dd yyyy HH:mm:ss')) AS year_sold,
  COUNT(*) AS total_sales
FROM `workspace`.`default`.`car_sales_data_clean`
GROUP BY YEAR(TO_TIMESTAMP(SUBSTRING(saledate, 5), 'MMM dd yyyy HH:mm:ss'))
ORDER BY year_sold;

-- Which car brands appear most frequently
SELECT make, COUNT(*) AS total_sales
FROM `workspace`.`default`.`car_sales_data_clean`
GROUP BY make
ORDER BY total_sales DESC
LIMIT 10;

--- Create cleaned and transformed table (simplified version)
CREATE OR REPLACE TABLE car_sales_final AS
SELECT
    year,
    make,
    model,
    trim,
    body,
    vin,

    -- Handle missing categorical values
    COALESCE(state, 'Unknown') AS state,
    COALESCE(transmission, 'Unknown') AS transmission,
    COALESCE(color, 'Unknown') AS color,
    COALESCE(interior, 'Unknown') AS interior,

    -- Numeric cleaning
    CAST(sellingprice AS DOUBLE) AS sellingprice,
    CAST(mmr AS DOUBLE) AS mmr,

    -- Handle missing odometer
    COALESCE(odometer, 0) AS odometer,

    -- Keep original sale date for now
    saledate,

    -- =====================
    -- FEATURE ENGINEERING
    -- =====================

    -- Total revenue
    CAST(sellingprice AS DOUBLE) AS total_revenue,

    -- Profit margin
    ROUND(
        ((CAST(sellingprice AS DOUBLE) - CAST(mmr AS DOUBLE))
        / CAST(sellingprice AS DOUBLE)) * 100,
        2
    ) AS profit_margin,

    -- Profit tier
    CASE
        WHEN ((CAST(sellingprice AS DOUBLE) - CAST(mmr AS DOUBLE))
             / CAST(sellingprice AS DOUBLE)) * 100 >= 20
            THEN 'High Margin'

        WHEN ((CAST(sellingprice AS DOUBLE) - CAST(mmr AS DOUBLE))
             / CAST(sellingprice AS DOUBLE)) * 100 BETWEEN 10 AND 19
            THEN 'Medium Margin'

        ELSE 'Low Margin'
    END AS profit_tier

FROM `workspace`.`default`.`car_sales_data_clean`

WHERE sellingprice IS NOT NULL
  AND make IS NOT NULL
  AND model IS NOT NULL;

  ---------------------------------------------------------------------------------------------------------------------------
  SELECT
    COUNT(*) AS total_rows,
    COUNT(sellingprice) AS sellingprice_count,
    COUNT(make) AS make_count,
    COUNT(model) AS model_count
FROM `workspace`.`default`.`car_sales_data_clean`;
  
SELECT COUNT(*) AS total_rows
FROM workspace.default.car_sales_final;

SELECT *
FROM `workspace`.`default`.`car_sales_data_clean`
LIMIT 10;

DESCRIBE `workspace`.`default`.`car_sales_data_clean`;

------------------------------------------------------------------------------------------------------------
-- Revenue generated by each car make
SELECT 
    make,
    COUNT(*) AS cars_sold,
    ROUND(SUM(sellingprice), 2) AS total_revenue,
    ROUND(AVG(sellingprice), 2) AS avg_selling_price
FROM car_sales_final
GROUP BY make
ORDER BY total_revenue DESC;

--- Best performing car models
SELECT 
    make,
    model,
    COUNT(*) AS units_sold,
    ROUND(SUM(sellingprice), 2) AS revenue
FROM car_sales_final
GROUP BY make, model
ORDER BY revenue DESC
LIMIT 10;

--- Sales performance by region/state
SELECT 
    state,
    COUNT(*) AS total_sales,
    ROUND(SUM(sellingprice), 2) AS total_revenue
FROM car_sales_final
GROUP BY state
ORDER BY total_revenue DESC;

--- Most popular body types
SELECT 
    body,
    COUNT(*) AS total_sales,
    ROUND(AVG(sellingprice), 2) AS avg_price
FROM car_sales_final
GROUP BY body
ORDER BY total_sales DESC;

--- Relationship between mileage and price
SELECT 
    ROUND(AVG(odometer), 0) AS avg_mileage,
    ROUND(AVG(sellingprice), 2) AS avg_price
FROM car_sales_final;

--- Sales distribution by car manufacturing year
SELECT 
    year,
    COUNT(*) AS cars_sold,
    ROUND(AVG(sellingprice), 2) AS avg_price
FROM car_sales_final
GROUP BY year
ORDER BY year DESC;

--- Profit margin categories
SELECT 
    profit_tier,
    COUNT(*) AS total_cars,
    ROUND(AVG(profit_margin), 2) AS avg_margin
FROM car_sales_final
GROUP BY profit_tier;
---------------------------------------------------------------------------------------------------------
-- =========================================
---BIG QUERY
-- =========================================
CREATE OR REPLACE TABLE car_sales_analytics AS


SELECT
    year,
    make,
    model,
    trim,
    body,
    transmission,
    vin,
    COALESCE(state, 'Unknown') AS state,
    COALESCE(color, 'Unknown') AS color,
    COALESCE(interior, 'Unknown') AS interior,

    -- condition is reserved in some SQL engines
    COALESCE(`condition`, 0) AS condition_score,
    COALESCE(odometer, 0) AS odometer,
    CAST(sellingprice AS DOUBLE) AS sellingprice,
    CAST(mmr AS DOUBLE) AS mmr,
    saledate,
  
    CASE
        WHEN `condition` >= 40 THEN 'Excellent'
        WHEN `condition` BETWEEN 30 AND 39 THEN 'Good'
        WHEN `condition` BETWEEN 20 AND 29 THEN 'Average'
        ELSE 'Poor'
    END AS condition_bracket,
    CASE
        WHEN odometer < 50000 THEN 'Low Mileage'
        WHEN odometer BETWEEN 50000 AND 100000 THEN 'Medium Mileage'
        ELSE 'High Mileage'
    END AS mileage_bracket,
    CASE
        WHEN sellingprice < 10000 THEN 'Budget'
        WHEN sellingprice BETWEEN 10000 AND 30000 THEN 'Mid Range'
        ELSE 'Luxury'
    END AS price_bracket,
    CAST(sellingprice AS DOUBLE) AS total_revenue,
    CAST(sellingprice AS DOUBLE) - CAST(mmr AS DOUBLE)
    AS price_difference,
    ROUND(
        (
            (CAST(sellingprice AS DOUBLE) - CAST(mmr AS DOUBLE))
            / CAST(sellingprice AS DOUBLE)
        ) * 100,
        2
    ) AS profit_margin,
    CASE
        WHEN (
            (CAST(sellingprice AS DOUBLE) - CAST(mmr AS DOUBLE))
            / CAST(sellingprice AS DOUBLE)
        ) * 100 >= 20
        THEN 'High Margin'
        WHEN (
            (CAST(sellingprice AS DOUBLE) - CAST(mmr AS DOUBLE))
            / CAST(sellingprice AS DOUBLE)
        ) * 100 BETWEEN 10 AND 19
        THEN 'Medium Margin'
        ELSE 'Low Margin'
    END AS profit_tier
FROM `workspace`.`default`.`car_sales_data_clean`
WHERE sellingprice IS NOT NULL
AND make IS NOT NULL
AND model IS NOT NULL;



SELECT
    saledate,

    YEAR(
        TO_TIMESTAMP(saledate, 'E MMM dd yyyy HH:mm:ss')
    ) AS sale_year,

    MONTH(
        TO_TIMESTAMP(saledate, 'E MMM dd yyyy HH:mm:ss')
    ) AS sale_month,

    DATE_FORMAT(
        TO_TIMESTAMP(saledate, 'E MMM dd yyyy HH:mm:ss'),
        'MMMM'
    ) AS month_name,

    DATE_FORMAT(
        TO_TIMESTAMP(saledate, 'E MMM dd yyyy HH:mm:ss'),
        'EEEE'
    ) AS day_name

FROM car_sales_analytics
LIMIT 10;
